Plugin 'altercation/vim-colors-solarized'
Plugin 'dag/vim-fish'
Plugin 'derekwyatt/vim-sbt'
Plugin 'derekwyatt/vim-scala'
Plugin 'fatih/vim-go'
Plugin 'tpope/vim-speeddating'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-markdown'
Plugin 'Yggdroot/indentLine'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'vim-pandoc/vim-pandoc-syntax'
Plugin 'scrooloose/syntastic'
Plugin 'nvie/vim-flake8'
Plugin 'vim-pandoc/vim-pandoc'
Plugin 'tpope/vim-fugitive'
" Plugin 'LnL7/vim-nix'


